name: CI/CD dev Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.1'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install
          # Проверяем установленные пакеты
          npm list --depth=0

      - name: Build project
        env:
          VITE_TPU_OAUTH_CLIENT_ID: ${{ secrets.VITE_TPU_OAUTH_CLIENT_ID }}
          VITE_API_BASE_URL: /dev/api
          VITE_API_AUTH_STATUS_URL: /auth/status
          VITE_API_RELOGIN_URL: /auth/refresh
          VITE_API_LOGIN_URL: /auth/login
          VITE_API_LOGOUT_URL: /auth/logout
          VITE_API_ME_URL: /users/me
          VITE_API_USERS_URL: /users
          VITE_API_PROJECTS_URL: /projects
          VITE_API_PROJECT_DRAFT_URL: /me/projects/draft
          VITE_API_TAGS_URL: /tags
          VITE_API_PARTNERS_URL: /partners
          VITE_API_COMPETENCIES_URL: /role-types
          VITE_API_SKILLS_URL: /skills
          VITE_API_CHECKPOINTS_URL: /projects/checkpoints
          VITE_OAUTH_AUTHORIZE_URL: https://oauth.tpu.ru/authorize

        run: |
          npm run build
          # Проверяем результат сборки
          ls dist

      - name: Verify build output
        run: |
          test -d dist || (echo "Директория dist не создана" && exit 1)
          test -f dist/index.html || (echo "Файл index.html отсутствует" && exit 1)

      - name: Deploy to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "~/tempMain"
